/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'
import { Route as DestinationDestinationIdRouteImport } from './routes/destination.$destinationId'
import { Route as AttractionsAttractionIdRouteImport } from './routes/attractions.$attractionId'

const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationDestinationIdRoute =
  DestinationDestinationIdRouteImport.update({
    id: '/destination/$destinationId',
    path: '/destination/$destinationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AttractionsAttractionIdRoute =
  AttractionsAttractionIdRouteImport.update({
    id: '/attractions/$attractionId',
    path: '/attractions/$attractionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/destination/$destinationId': typeof DestinationDestinationIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/': typeof TripsIndexRoute
  '/attractions/$attractionId': typeof AttractionsAttractionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/destination/$destinationId': typeof DestinationDestinationIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips': typeof TripsIndexRoute
  '/attractions/$attractionId': typeof AttractionsAttractionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/destination/$destinationId': typeof DestinationDestinationIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/': typeof TripsIndexRoute
  '/attractions/$attractionId': typeof AttractionsAttractionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/destination/$destinationId'
    | '/trips/$tripId'
    | '/trips/'
    | '/attractions/$attractionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/map' | '/destination/$destinationId' | '/trips/$tripId' | '/trips' | '/attractions/$attractionId'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/destination/$destinationId'
    | '/trips/$tripId'
    | '/trips/'
    | '/attractions/$attractionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  DestinationDestinationIdRoute: typeof DestinationDestinationIdRoute
  TripsTripIdRoute: typeof TripsTripIdRoute
  TripsIndexRoute: typeof TripsIndexRoute
  AttractionsAttractionIdRoute: typeof AttractionsAttractionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/$destinationId': {
      id: '/destination/$destinationId'
      path: '/destination/$destinationId'
      fullPath: '/destination/$destinationId'
      preLoaderRoute: typeof DestinationDestinationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractions/$attractionId': {
      id: '/attractions/$attractionId'
      path: '/attractions/$attractionId'
      fullPath: '/attractions/$attractionId'
      preLoaderRoute: typeof AttractionsAttractionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  DestinationDestinationIdRoute: DestinationDestinationIdRoute,
  TripsTripIdRoute: TripsTripIdRoute,
  TripsIndexRoute: TripsIndexRoute,
  AttractionsAttractionIdRoute: AttractionsAttractionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
