/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'
import { Route as HighlightHighlightIdRouteImport } from './routes/highlight.$highlightId'
import { Route as EventEventIdRouteImport } from './routes/event.$eventId'
import { Route as DestinationDestinationIdRouteImport } from './routes/destination.$destinationId'
import { Route as AccommodationAccommodationIdRouteImport } from './routes/accommodation.$accommodationId'

const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightHighlightIdRoute = HighlightHighlightIdRouteImport.update({
  id: '/highlight/$highlightId',
  path: '/highlight/$highlightId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationDestinationIdRoute =
  DestinationDestinationIdRouteImport.update({
    id: '/destination/$destinationId',
    path: '/destination/$destinationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccommodationAccommodationIdRoute =
  AccommodationAccommodationIdRouteImport.update({
    id: '/accommodation/$accommodationId',
    path: '/accommodation/$accommodationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/accommodation/$accommodationId': typeof AccommodationAccommodationIdRoute
  '/destination/$destinationId': typeof DestinationDestinationIdRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/highlight/$highlightId': typeof HighlightHighlightIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/accommodation/$accommodationId': typeof AccommodationAccommodationIdRoute
  '/destination/$destinationId': typeof DestinationDestinationIdRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/highlight/$highlightId': typeof HighlightHighlightIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/accommodation/$accommodationId': typeof AccommodationAccommodationIdRoute
  '/destination/$destinationId': typeof DestinationDestinationIdRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/highlight/$highlightId': typeof HighlightHighlightIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/accommodation/$accommodationId'
    | '/destination/$destinationId'
    | '/event/$eventId'
    | '/highlight/$highlightId'
    | '/trips/$tripId'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/accommodation/$accommodationId'
    | '/destination/$destinationId'
    | '/event/$eventId'
    | '/highlight/$highlightId'
    | '/trips/$tripId'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/accommodation/$accommodationId'
    | '/destination/$destinationId'
    | '/event/$eventId'
    | '/highlight/$highlightId'
    | '/trips/$tripId'
    | '/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  AccommodationAccommodationIdRoute: typeof AccommodationAccommodationIdRoute
  DestinationDestinationIdRoute: typeof DestinationDestinationIdRoute
  EventEventIdRoute: typeof EventEventIdRoute
  HighlightHighlightIdRoute: typeof HighlightHighlightIdRoute
  TripsTripIdRoute: typeof TripsTripIdRoute
  TripsIndexRoute: typeof TripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlight/$highlightId': {
      id: '/highlight/$highlightId'
      path: '/highlight/$highlightId'
      fullPath: '/highlight/$highlightId'
      preLoaderRoute: typeof HighlightHighlightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/$destinationId': {
      id: '/destination/$destinationId'
      path: '/destination/$destinationId'
      fullPath: '/destination/$destinationId'
      preLoaderRoute: typeof DestinationDestinationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation/$accommodationId': {
      id: '/accommodation/$accommodationId'
      path: '/accommodation/$accommodationId'
      fullPath: '/accommodation/$accommodationId'
      preLoaderRoute: typeof AccommodationAccommodationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  AccommodationAccommodationIdRoute: AccommodationAccommodationIdRoute,
  DestinationDestinationIdRoute: DestinationDestinationIdRoute,
  EventEventIdRoute: EventEventIdRoute,
  HighlightHighlightIdRoute: HighlightHighlightIdRoute,
  TripsTripIdRoute: TripsTripIdRoute,
  TripsIndexRoute: TripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
